# Generated by Django 3.2.9 on 2022-01-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('type', models.CharField(choices=[('fruit', 'fruit')], default='fruit', max_length=30, verbose_name='Types')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('barcode', models.CharField(max_length=128, verbose_name='barcode')),
                ('image', models.ImageField(upload_to='media/% Y/% m/% d/')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
