# Generated by Django 3.2.9 on 2022-01-30 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('sku', models.CharField(max_length=128, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('qrcode', models.CharField(max_length=128, verbose_name='QR Code')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('status', models.CharField(max_length=64, verbose_name='Status')),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='items.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.fridge', verbose_name='Fridge')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item', verbose_name='Item')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.shelf', verbose_name='Shelf')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('shelf', 'item')},
            },
        ),
        migrations.CreateModel(
            name='StockMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('movement_type', models.CharField(choices=[('buy', 'Buy'), ('transfer', 'Transfer'), ('use', 'Use'), ('garbage', 'Garbage')], max_length=50, verbose_name='Movement Type')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('movement_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Movement Time')),
                ('movement_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_stock_set', to='items.stock', verbose_name='Movement From')),
                ('movement_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_stock_set', to='items.stock', verbose_name='Movement To')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
            },
        ),
    ]
