# Generated by Django 3.2.9 on 2022-01-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='type',
            new_name='item_type',
        ),
    ]
