# Generated by Django 3.2.9 on 2022-01-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelves', '0002_connectionuserstorages'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='quantity')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shelves.connectionuserstorages', verbose_name='Connection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.items', verbose_name='Items')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('direction', models.IntegerField(verbose_name='direction')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='quantity')),
                ('item_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.itemlocations', verbose_name='item location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
