# Generated by Django 3.2.9 on 2022-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
            options={
                'verbose_name': 'shelve',
                'verbose_name_plural': 'shelves',
            },
        ),
    ]
