# Generated by Django 3.2.9 on 2022-01-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionUserStorages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shelves.shelves', verbose_name='shelve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='user')),
            ],
        ),
    ]
